cd release
rd /Q /S ..\..\html
md ..\..\html
WikiToHtmlConverter.exe ..\..\wiki\ ..\..\html
cd ..\..\html
del TOCArticles.html
md "External Resources"
md "FAQ"
md "Function List"
md "How To"
md "Introduction"
md "Scripts"
md "Tutorials"
md "Function List\Engine"
md "Function List\Entities, Objects, & Primitives"
md "Function List\Math"
md "Function List\Misc"
md "Function List\Mouse"
md "Function List\Physics & Collisions"
md "Function List\Rendering & Particles"
md "Function List\Resources, Textures, & Materials"
md "Function List\Scene, Terrain, & Environment"
md "Function List\Skeletons, Splines, & Animation"
md "Function List\Text, Sprites, Overlays, & GUI"
md "Function List\Entities, Objects, & Primitives\Billboard"
md "Function List\Entities, Objects, & Primitives\Entity"
md "Function List\Physics & Collisions\Newton Physics"
md "Function List\Rendering & Particles\Compositor"
md "Function List\Rendering & Particles\Particle System"
md "Function List\Resources, Textures, & Materials\Material"
md "Function List\Scene, Terrain, & Environment\Camera Control System"
md "Function List\Scene, Terrain, & Environment\Paged Geometry"
md "Function List\Skeletons, Splines, & Animation\Animation"
md "Function List\Text, Sprites, Overlays, & GUI\GUI"
md "Function List\Text, Sprites, Overlays, & GUI\Overlay"
md "Function List\Text, Sprites, Overlays, & GUI\GUI\Window"
md "Function List\Timers & Performance"
md "Scripts\Compositors"
md "Scripts\Fonts"
md "Scripts\Materials"
md "Scripts\Overlays"
md "Scripts\Particles"
md "Tutorials\Advanced Tutorials"
md "Tutorials\Basic Tutorials"
move /Y externalresources.html ".\External Resources\"
move /Y faq.html ".\Faq\"
move /Y howto*.html ".\How To\"
move /Y Features.html ".\Introduction\"
move /Y License.html ".\Introduction\"
move /Y Welcome.html ".\Introduction\"
move /Y Tutorials.html ".\Tutorials\"
move /Y BasicTutorial*.html ".\Tutorials\Basic Tutorials\"
move /Y AdvancedTutorial*.html ".\Tutorials\Advanced Tutorials\"
move /Y UsingASkydomeTutorial.html ".\Tutorials\Basic Tutorials\"
move /Y scripts.html ".\scripts\"
move /Y compositor*scripts.html ".\scripts\compositors\"
move /Y fontscripts.html ".\scripts\fonts\"
move /Y material*scripts.html ".\scripts\materials\"
move /Y overlay*scripts.html ".\scripts\overlays\"
move /Y particle*scripts.html ".\scripts\particles\"
move /Y enginefunctions.html ".\Function List\Engine\"
move /Y light*functions.html ".\Function List\Entities, Objects, & Primitives\"
move /Y manualobject*functions.html ".\Function List\Entities, Objects, & Primitives\"
move /Y mesh*functions.html ".\Function List\Entities, Objects, & Primitives\"
move /Y movableobj*functions.html ".\Function List\Entities, Objects, & Primitives\"
move /Y plane*functions.html ".\Function List\Entities, Objects, & Primitives\"
move /Y rectangle2d*functions.html ".\Function List\Entities, Objects, & Primitives\"
move /Y billboard*functions.html ".\Function List\Entities, Objects, & Primitives\Billboard\"
move /Y ribbon*functions.html ".\Function List\Entities, Objects, & Primitives\Billboard\"
move /Y *entityfunctions.html ".\Function List\Entities, Objects, & Primitives\Entity\"
move /Y euler*functions.html ".\Function List\Math\"
move /Y matrix*functions.html ".\Function List\Math\"
move /Y vector*functions.html ".\Function List\Math\"
move /Y miscfunctions.html ".\Function List\Misc\"
move /Y mousefunctions.html ".\Function List\Mouse\"
move /Y collision*functions.html ".\Function List\Physics & Collisions\"
move /Y ray*functions.html ".\Function List\Physics & Collisions\"
move /Y newton*functions.html ".\Function List\Physics & Collisions\Newton Physics\"
move /Y gpu*functions.html ".\Function List\Rendering & Particles\"
move /Y composit*functions.html ".\Function List\Rendering & Particles\compositor\"
move /Y particle*functions.html ".\Function List\Rendering & Particles\particle system\"
move /Y texture*functions.html ".\Function List\Resources, Textures, & Materials\"
move /Y resource*functions.html ".\Function List\Resources, Textures, & Materials\"
move /Y material*functions.html ".\Function List\Resources, Textures, & Materials\material\"
move /Y passfunctions.html ".\Function List\Resources, Textures, & Materials\material\"
move /Y techniquefunctions.html ".\Function List\Resources, Textures, & Materials\material\"
move /Y camerafunctions.html ".\Function List\Scene, Terrain, & Environment\"
move /Y pssm*functions.html ".\Function List\Scene, Terrain, & Environment\"
move /Y lightmap*functions.html ".\Function List\Scene, Terrain, & Environment\"
move /Y scene*functions.html ".\Function List\Scene, Terrain, & Environment\"
move /Y skyxfunctions.html ".\Function List\Scene, Terrain, & Environment\"
move /Y staticgeo*functions.html ".\Function List\Scene, Terrain, & Environment\"
move /Y viewportfunctions.html ".\Function List\Scene, Terrain, & Environment\"
move /Y cssfunctions.html ".\Function List\Scene, Terrain, & Environment\Camera Control System\"
move /Y *camerafunctions.html ".\Function List\Scene, Terrain, & Environment\Camera Control System\"
move /Y grass*functions.html ".\Function List\Scene, Terrain, & Environment\Paged Geometry\"
move /Y *loader*functions.html ".\Function List\Scene, Terrain, & Environment\Paged Geometry\"
move /Y pagedgeo*functions.html ".\Function List\Scene, Terrain, & Environment\Paged Geometry\"
move /Y bonefunctions.html ".\Function List\Skeletons, Splines, & Animation\"
move /Y simplesplinefunctions.html ".\Function List\Skeletons, Splines, & Animation\"
move /Y skeletonfunctions.html ".\Function List\Skeletons, Splines, & Animation\"
move /Y transformkeyframefunctions.html ".\Function List\Skeletons, Splines, & Animation\"
move /Y animation*functions.html ".\Function List\Skeletons, Splines, & Animation\Animation\"
move /Y fontfunctions.html ".\Function List\Text, Sprites, Overlays, & GUI\"
move /Y movabletextfunctions.html ".\Function List\Text, Sprites, Overlays, & GUI\"
move /Y spritefunctions.html ".\Function List\Text, Sprites, Overlays, & GUI\"
move /Y textfunctions.html ".\Function List\Text, Sprites, Overlays, & GUI\"
move /Y *overlay*functions.html ".\Function List\Text, Sprites, Overlays, & GUI\overlay\"
move /Y guiImageSetfunctions.html ".\Function List\Text, Sprites, Overlays, & GUI\gui\"
move /Y guitexturefunctions.html ".\Function List\Text, Sprites, Overlays, & GUI\gui\"
move /Y gui*functions.html ".\Function List\Text, Sprites, Overlays, & GUI\GUI\Window\"
move /Y TimerFunctions.html ".\Function List\Timers & Performance\"
move /Y PerformanceFunctions.html ".\Function List\Timers & Performance\"
